/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.contentpanel.admins;

import database.DatabaseTable;
import gui.MainJFrame;
import gui.LoginPanel;
import gui.contentpanel.PnlHome;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import people.IAdmin;
import wrappers.DesktopWrapper;

/**
 *
 * @author 10512691
 */
public class PnlEditAdmin extends javax.swing.JFrame {

    private static PnlHome parent;
    private static IAdmin  editingAdmin;
    /**
     * Creates new form PnlEditAdmin
     * @param parent
     * @param admin
     */
    public PnlEditAdmin(PnlHome parent, IAdmin admin) {
        initComponents();
        
        PnlEditAdmin.parent = parent;
        PnlEditAdmin.editingAdmin = admin;
        
        initPanel();
        initHelp();
        
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setResizable(false);
    }
    
    private void initPanel() {
        txtEmail.setText(editingAdmin.getEmail());
        txtEmail.setEditable(false);
        loading_icon_lbl.setVisible(false);
    }
    
    private void initHelp() {
        helpEmail.setToolTipText("The email address for the admin account.");
        helpOldPassword.setToolTipText("Enter the old password of the account.");
        helpNewPassword.setToolTipText("Enter the new password for the account.");
    }
    
    private void editable(boolean flag) {
        loading_icon_lbl.setVisible(!flag);
        txtOldPassword.setEditable(flag);
        txtNewPassword.setEditable(flag);
        txtNewPasswordCheck.setEditable(flag);
        btnCancel.setEnabled(flag);
        btnSave.setEnabled(flag);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackground2 = new javax.swing.JPanel();
        lblEmail = new javax.swing.JLabel();
        lblNewPassword = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblDetailsTitle = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        helpEmail = new javax.swing.JLabel();
        helpNewPassword = new javax.swing.JLabel();
        txtNewPassword = new javax.swing.JPasswordField();
        loading_icon_lbl = new javax.swing.JLabel();
        lblOldPassword = new javax.swing.JLabel();
        txtOldPassword = new javax.swing.JPasswordField();
        lblPasswordReEnter1 = new javax.swing.JLabel();
        txtNewPasswordCheck = new javax.swing.JPasswordField();
        helpOldPassword = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlBackground2.setBackground(new java.awt.Color(51, 51, 51));

        lblEmail.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("Email:");

        lblNewPassword.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblNewPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblNewPassword.setText("<html>New <br>Password:</html>");

        txtEmail.setEditable(false);
        txtEmail.setBackground(new java.awt.Color(51, 51, 51));
        txtEmail.setForeground(new java.awt.Color(250, 250, 250));

        lblDetailsTitle.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        lblDetailsTitle.setForeground(new java.awt.Color(250, 250, 250));
        lblDetailsTitle.setText("Admin Details");

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        helpEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/helpIconNew.png"))); // NOI18N

        helpNewPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/helpIconNew.png"))); // NOI18N

        txtNewPassword.setBackground(new java.awt.Color(51, 51, 51));

        loading_icon_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/loading_icon.gif"))); // NOI18N

        lblOldPassword.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblOldPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblOldPassword.setText("<html>Old <br>Password:</html>");

        txtOldPassword.setBackground(new java.awt.Color(51, 51, 51));

        lblPasswordReEnter1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblPasswordReEnter1.setForeground(new java.awt.Color(255, 255, 255));
        lblPasswordReEnter1.setText("Re-Enter:");

        txtNewPasswordCheck.setBackground(new java.awt.Color(51, 51, 51));

        helpOldPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/helpIconNew.png"))); // NOI18N

        javax.swing.GroupLayout pnlBackground2Layout = new javax.swing.GroupLayout(pnlBackground2);
        pnlBackground2.setLayout(pnlBackground2Layout);
        pnlBackground2Layout.setHorizontalGroup(
            pnlBackground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackground2Layout.createSequentialGroup()
                .addGroup(pnlBackground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlBackground2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlBackground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackground2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblDetailsTitle)
                                .addGap(135, 135, 135))
                            .addGroup(pnlBackground2Layout.createSequentialGroup()
                                .addGroup(pnlBackground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlBackground2Layout.createSequentialGroup()
                                        .addComponent(lblOldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtOldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlBackground2Layout.createSequentialGroup()
                                        .addComponent(lblNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(pnlBackground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pnlBackground2Layout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(pnlBackground2Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(18, 18, 18)
                                .addGroup(pnlBackground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(helpOldPassword)
                                    .addComponent(helpNewPassword))
                                .addGap(0, 2, Short.MAX_VALUE))))
                    .addGroup(pnlBackground2Layout.createSequentialGroup()
                        .addComponent(loading_icon_lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlBackground2Layout.createSequentialGroup()
                        .addComponent(lblEmail)
                        .addGap(315, 315, 315)
                        .addComponent(helpEmail)))
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(pnlBackground2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPasswordReEnter1)
                .addGap(18, 18, 18)
                .addComponent(txtNewPasswordCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBackground2Layout.setVerticalGroup(
            pnlBackground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackground2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lblDetailsTitle)
                .addGap(18, 18, 18)
                .addGroup(pnlBackground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlBackground2Layout.createSequentialGroup()
                        .addGroup(pnlBackground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlBackground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblEmail)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(helpEmail))
                        .addGap(18, 18, 18)
                        .addGroup(pnlBackground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtOldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(helpOldPassword)))
                    .addComponent(lblOldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(pnlBackground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(helpNewPassword)
                        .addComponent(txtNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBackground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPasswordReEnter1)
                    .addComponent(txtNewPasswordCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlBackground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBackground2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(pnlBackground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSave)
                            .addComponent(btnCancel))
                        .addContainerGap())
                    .addComponent(loading_icon_lbl, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed

        int dialog = JOptionPane.showConfirmDialog(this, "Are you sure you want to cancel?", "Confirm", JOptionPane.OK_CANCEL_OPTION);
        if (dialog == JOptionPane.OK_OPTION) {
            dispose();
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        if (txtNewPassword.getText().equals(txtNewPasswordCheck.getText())) {

            int result = JOptionPane.showConfirmDialog(this, "Are you ready to save? Changes will immediately become live.", "Save Artist", JOptionPane.OK_CANCEL_OPTION);

            if (result == JOptionPane.OK_OPTION) {
                
                editable(false);
                
                SwingWorker<String, Object> sWorker = new SwingWorker() {
                    @Override
                    public String doInBackground() {
                        try {
                            if (DesktopWrapper.getInstance().checkAdminPassword(txtEmail.getText(), txtOldPassword.getText())) {
                                
                                editingAdmin.setPassword(txtNewPassword.getText());
                                DesktopWrapper.getInstance().updateObject(editingAdmin, DatabaseTable.ADMIN);
                                
                                PnlEditAdmin.this.dispose();
                                parent.populateAdminTable();
                                //parent.displayText("Password for " + editingAdmin.getEmail() + " updated!");
                                done();
                                
                            } else {
                                JOptionPane.showMessageDialog(PnlEditAdmin.this, "Email / password combination didn't match. Please try again.");
                                done();
                            }
                        } 
                        catch (IOException ex) 
                        {
                            JOptionPane.showMessageDialog(PnlEditAdmin.this, "IOException  " +  ex.getMessage());
                            done();
                        }
                        catch (IllegalArgumentException ex) 
                        {
                            JOptionPane.showMessageDialog(PnlEditAdmin.this, ex.getMessage());
                            done();
                        }

                        return "";
                    }

                    @Override
                    protected void done() {
                        editable(true);
                    }
                };

                sWorker.execute();
            }
        } else {
            JOptionPane.showMessageDialog(this, "New passwords do not match. Please try again.");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PnlEditAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PnlEditAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PnlEditAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PnlEditAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PnlEditAdmin(parent, editingAdmin).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel helpEmail;
    private javax.swing.JLabel helpNewPassword;
    private javax.swing.JLabel helpOldPassword;
    private javax.swing.JLabel lblDetailsTitle;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNewPassword;
    private javax.swing.JLabel lblOldPassword;
    private javax.swing.JLabel lblPasswordReEnter1;
    private javax.swing.JLabel loading_icon_lbl;
    private javax.swing.JPanel pnlBackground2;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtNewPassword;
    private javax.swing.JPasswordField txtNewPasswordCheck;
    private javax.swing.JPasswordField txtOldPassword;
    // End of variables declaration//GEN-END:variables
}
