/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.contentpanel.bookings;

import events.IChildEvent;
import events.IParentEvent;
import gui.contentpanel.events.PnlEvents;
import gui.contentpanel.users.PnlEditUser;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import people.ICustomer;
import tickets.ITicket;
import wrappers.DesktopWrapper;

/**
 *
 * @author Dominic
 */
public class PnlCustomerBooking extends javax.swing.JFrame {

    private  List<IParentEvent> allParentEvents = new ArrayList<>();
    private List<IChildEvent> childEvents = new ArrayList<>();
    private List<ITicket> tickets = new ArrayList<>();
    private ComboBoxModel childEventsModel;
    private DefaultListModel listModel;
    private ComboBoxModel ticketsModel;
    private ICustomer user;
    private PnlEditUser parent;
    
    /**
     * Creates new form customerBooking
     */
    public PnlCustomerBooking() {
        listModel = new DefaultListModel();
        childEventsModel = new DefaultComboBoxModel();
        ticketsModel = new DefaultComboBoxModel();
        loadParentEvents();
        initComponents();
        loading_icon_lbl.setVisible(false);
        
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }
    
    public void setParent(PnlEditUser parent) {
        this.parent = parent;
    }
    
    private void editable(boolean flag) {
        jScrollPane1.setEnabled(flag);
        cmbChildEvents.setEnabled(flag);
        cmbTickets.setEnabled(flag);
        spnQuantity.setEnabled(flag);
        btnBuyNow.setEnabled(flag);
        btnCancel.setEnabled(flag);
        loading_icon_lbl.setVisible(!flag);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        pnlBackground = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstParentEvents = new javax.swing.JList<>();
        cmbChildEvents = new javax.swing.JComboBox<>();
        cmbTickets = new javax.swing.JComboBox<>();
        spnQuantity = new javax.swing.JSpinner();
        lblName1 = new javax.swing.JLabel();
        lblName2 = new javax.swing.JLabel();
        lblName3 = new javax.swing.JLabel();
        lblName4 = new javax.swing.JLabel();
        btnBuyNow = new javax.swing.JButton();
        txtBooking = new javax.swing.JLabel();
        loading_icon_lbl = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();

        lblName.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("Forename : ");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlBackground.setBackground(new java.awt.Color(51, 51, 51));

        lstParentEvents.setModel(listModel);
        lstParentEvents.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstParentEvents.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstParentEventsValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstParentEvents);

        cmbChildEvents.setModel(childEventsModel);
        cmbChildEvents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbChildEventsActionPerformed(evt);
            }
        });
        cmbChildEvents.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cmbChildEventsPropertyChange(evt);
            }
        });

        cmbTickets.setModel(ticketsModel);

        spnQuantity.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        lblName1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblName1.setForeground(new java.awt.Color(255, 255, 255));
        lblName1.setText("Parent Events");

        lblName2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblName2.setForeground(new java.awt.Color(255, 255, 255));
        lblName2.setText("Child Events");

        lblName3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblName3.setForeground(new java.awt.Color(255, 255, 255));
        lblName3.setText("Tickets");

        lblName4.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblName4.setForeground(new java.awt.Color(255, 255, 255));
        lblName4.setText("Quantity");

        btnBuyNow.setText("Pay Now");
        btnBuyNow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuyNowMouseClicked(evt);
            }
        });

        txtBooking.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        txtBooking.setForeground(new java.awt.Color(255, 255, 255));
        txtBooking.setText("Make A Booking For ");

        loading_icon_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/loading_icon.gif"))); // NOI18N

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBackgroundLayout = new javax.swing.GroupLayout(pnlBackground);
        pnlBackground.setLayout(pnlBackgroundLayout);
        pnlBackgroundLayout.setHorizontalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(txtBooking)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(lblName1)))
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroundLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loading_icon_lbl))
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(lblName2))
                            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbChildEvents, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbTickets, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(lblName3))
                            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnBuyNow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                                        .addComponent(lblName4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(spnQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 6, Short.MAX_VALUE))))
        );
        pnlBackgroundLayout.setVerticalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(txtBooking)
                .addGap(18, 18, 18)
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addComponent(lblName1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblName2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbChildEvents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblName3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbTickets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(spnQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblName4))
                                .addGap(57, 57, 57)
                                .addComponent(btnBuyNow, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCancel))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroundLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(loading_icon_lbl))))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lstParentEventsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstParentEventsValueChanged
        loading_icon_lbl.setVisible(true);
        SwingWorker<String, Object> worker = new SwingWorker() {
            @Override
            protected Object doInBackground() throws Exception {
                loadChildEvents();
                loading_icon_lbl.setVisible(false);
                return "";
            }
        };
        worker.execute();
    }//GEN-LAST:event_lstParentEventsValueChanged

    private void cmbChildEventsPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cmbChildEventsPropertyChange
            
    }//GEN-LAST:event_cmbChildEventsPropertyChange

    private void cmbChildEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbChildEventsActionPerformed
        if(!cmbChildEvents.getSelectedItem().equals("No Events Found"))
        {
            try {
                tickets = childEvents.get(cmbChildEvents.getSelectedIndex()).getTickets();
                cmbTickets.setModel(new DefaultComboBoxModel());
                for (ITicket ticket : tickets) {
                    cmbTickets.addItem(ticket.getType() + " - " + utilities.Formatter.formatPrice(ticket.getPrice()));
                }
            } catch (IOException ex) {
                    cmbTickets.setModel(new DefaultComboBoxModel());
                    cmbTickets.addItem(("IO ERROR"));
            }
        }
    }//GEN-LAST:event_cmbChildEventsActionPerformed

    private void btnBuyNowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuyNowMouseClicked

        if (user != null) {
            if(cmbTickets.getSelectedIndex() != -1 && !tickets.isEmpty()) {

                ITicket ticket = tickets.get(cmbTickets.getSelectedIndex());
                Integer quantity = (Integer) spnQuantity.getValue();

                String question = "Are you sure you want to book " + quantity.toString() +
                        " " + ticket.getType() + " tickets for " + user.getFirstName() + " " +  user.getLastName() + "?";

                if(JOptionPane.showConfirmDialog(this,question,"Customer Booking", 0) == JOptionPane.OK_OPTION) {
                    
                    Thread t = new Thread(new Runnable() {
                        @Override
                        public void run() {
                            try {
                                user.addOrder(DesktopWrapper.getInstance().makeCustomerBooking(user, ticket, quantity));
                                dispose();
                                editable(true);
                            }
                            catch (IllegalArgumentException ex) {
                                JOptionPane.showMessageDialog(PnlCustomerBooking.this, "Cannot make booking.\n\n" + ex.getMessage());
                            }
                            catch (IOException ex) {
                                JOptionPane.showMessageDialog(PnlCustomerBooking.this, "There's been an error creating the booking.\n\n"
                                        + "Please check the Customer Tickets table for confirmation of result.");
                            }
                            finally {
                                parent.populateTable();
                            }
                        }

                    }, "OrderThread");
                    
                    editable(false);
                    t.start();
                }
            }
            else {
                JOptionPane.showMessageDialog(this,"Please select a ticket to buy first");
            }
        }
        else {
            JOptionPane.showMessageDialog(this, "Error : No User Selected. \n\n"
                   + "Please Contact a developer about this issue!");
            dispose();
        }
    }//GEN-LAST:event_btnBuyNowMouseClicked

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Are you sure you want to cancel this booking?") == JOptionPane.OK_OPTION) {
            dispose();
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PnlCustomerBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PnlCustomerBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PnlCustomerBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PnlCustomerBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PnlCustomerBooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuyNow;
    private javax.swing.JButton btnCancel;
    private javax.swing.JComboBox<String> cmbChildEvents;
    private javax.swing.JComboBox<String> cmbTickets;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblName1;
    private javax.swing.JLabel lblName2;
    private javax.swing.JLabel lblName3;
    private javax.swing.JLabel lblName4;
    private javax.swing.JLabel loading_icon_lbl;
    private javax.swing.JList<String> lstParentEvents;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JSpinner spnQuantity;
    private javax.swing.JLabel txtBooking;
    // End of variables declaration//GEN-END:variables

    private void loadParentEvents() {
        try {
             allParentEvents = DesktopWrapper.getInstance().refreshParentEvents();
           for (IParentEvent currEvent : allParentEvents)
            {
                listModel.addElement(currEvent.getName());
            }
    
        } catch (IOException ex) {
         listModel.addElement("No Events Found");
        }
    }
    
    public void setUser(ICustomer user) {
        this.user = user;
        txtBooking.setText("Making  A Booking For " + user.getFirstName() + " " + user.getLastName());
    }

    private void loadChildEvents() {
        if(lstParentEvents.getSelectedIndex() != -1)
        {
            IParentEvent currParentEvent = allParentEvents.get(lstParentEvents.getSelectedIndex());
            try {
                childEvents = currParentEvent.getChildEvents();
                cmbChildEvents.setModel(new DefaultComboBoxModel());
                
                if(childEvents.isEmpty()) {
                 cmbChildEvents.addItem("No Events Found");
                 cmbTickets.setEnabled(false);

                }
                else {
                    cmbTickets.setEnabled(true);
                    cmbTickets.setModel(new DefaultComboBoxModel());
                    cmbTickets.addItem("No Tickets Found");
                    for (IChildEvent event : childEvents) {
                        cmbChildEvents.addItem(event.getName());
                    }
                }

            } catch (IOException ex) {
                Logger.getLogger(PnlEvents.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
}
